### ISSUE TITLE
Running the softhand from soft_hand_ros_control

### ISSUE THREAD

**Issue by ghost** [CentroEPiaggio/pisa-iit-soft-hand#15]
Hi,

I'm currently trying to get the softhand running from soft_hand_ros_control. Unfortunately, so far, I did not succeed. Here's what I did:
1. cloned the pisa-iit-soft-hand repository
2. cloned the necessary ros_control package containing the necessary extension for controlling the soft hand
3. intialized and updated the handtools and qbAPI submodules
4. compiled the qbAPI, handtools and finally the soft_hand_ros_control

As I am currently working with the left hand, I tailored a launch script (two-hands-example) that allows me to only use the left hand. Upon starting the launch script using roslaunch with the real hand turned on the simulator turned off, I get the following output:

[ INFO] [1452845645.668951986]: Handling joint: left_hand_synergy_joint
[ INFO] [1452845645.669039140]: Register state and position interfaces
[ INFO] [1452845645.839601331]: rviz version 1.11.10
[ INFO] [1452845645.839691169]: compiled against OGRE version 1.8.1 (Byatis)
[INFO] [WallTime: 1452845646.351047] Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1452845646.612255268]: Stereo is NOT SUPPORTED
[ INFO] [1452845646.612611568]: OpenGl version: 3 (GLSL 1.3).
::��[ INFO] [1452845647.479951453]: Done initialization !
::��[INFO] [WallTime: 1452845647.558191] Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [WallTime: 1452845647.559737] Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [WallTime: 1452845647.561138] Loading controller: joint_state_controller
[INFO] [WallTime: 1452845647.624128] Loading controller: joint_position_controller
[INFO] [WallTime: 1452845647.680793] Controller Spawner: Loaded controllers: joint_state_controller, joint_position_controller

which implies that the controllers are up and running and the hand has been found and initialized. However, upon issuing a command via 

rostopic pub /soft_hand/joint_position_controller/command std_msgs/Float64 "data: 0.1"

the hand doesn't move (either the real one nor in RViz). I also did some debugging and realized the "void SHHW::write()", which to my understanding moves the real hand, is never actually executed (I've put a ROS_INFO whose message is never printed to the console).

I'm attaching my launch file and the controller config below (they were only renamed to txt for being able to upload them).

Any help would be greatly appreciated - thanks a lot in advance!

As a side note, I'm able to move the hand using the handtools from the command line.

Best,

Philipp

[controllers.yaml.txt](https://github.com/CentroEPiaggio/pisa-iit-soft-hand/files/91601/controllers.yaml.txt)
[names.yaml.txt](https://github.com/CentroEPiaggio/pisa-iit-soft-hand/files/91600/names.yaml.txt)
[soft_hand.launch.txt](https://github.com/CentroEPiaggio/pisa-iit-soft-hand/files/91602/soft_hand.launch.txt)

**Comment by carlosjoserg** [comment]
Hi @lokalmatador, I understand from your email that you managed to solve this.

My guesses were going to be:
- In step 2, did you check out to the `multi-robot-test` branch?
- In the launch file, you have the `use_robot_sim` default to `true`, and `hand_enabled` default to `false`. Did you switch them? (you don't need to edit the file, you can switch at command time)?

Could you confirm this, and if not, what did you do?
Thanks

**Comment by carlosjoserg** [comment]
Hi again @lokalmatador, according to your email (I use the same issue because I think they are related):

> I managed to get the SoftHand running using the adaptive_example from inside my private catkin workspace (call it A). I have the issue that in another workspace (call it B) that contains sources related to the project where we want to use the hand, the hand doesn't work. That is:
> 1. the node is started and the hand is initialized properly
> 2. I can list all relevant topics (in my case: /soft_hand/joint_trajectory_controller/command)
> 3. echoing the hand's state does not show me anything on the console (which is weird)
> 4. sending commands via /soft_hand/joint_trajectory_controller/command does not move the hand, either in Rviz nor the real hand
> 
> All the above works nicely in workspace A but not in workspace B. Further, for all of this Gazebo is not running, so there cannot be an interference with topics. Have you ever experienced such strange behavior?

Looks like an overlay problem, you need to be sure that the first find is the forked version of the ros control packages.

You can check that by doing `roscd ANY_ROS_CONTROL_PACKAGE` and see where it goes, either A, B or the /opt/ros/indigo/....

**Comment by ghost** [comment]
Hi Carlos,

I already thought about that overlay, but roscd goes into the modified ros-control package. Maybe it's related to a dependency of ros-control to some ros-package that also has been modified in our project's workspace. Other than that, I have no more clue what could cause this, but I will keep you updated. Anyways, thanks for your help!

**Comment by carlosjoserg** [comment]
> dependency of ros-control to some ros-package that also has been modified in our project's workspace

That'd be very unlucky!

Nevertheless, the modifications in ours only concern (as far as I remember) the `transmission_interface` package, and one affects the URDF spec, which might be the cause. The commits are:

CentroEPiaggio/ros_control@ab2c1f6bdf9698a0640652cf4c29c583ac960152  --> This shouldn't be a problem)

CentroEPiaggio/ros_control@82cf28ae87f202009b34aa1abacfb115d5fcdaed --> This CAN be a problem, and this is something I want to avoid... I already know how I would like it to be, only that I haven't got the time.
