### ISSUE TITLE
Wrong `joint_position_prev` update

### ISSUE THREAD

**Issue by qbrobotics-AT** [CentroEPiaggio/pisa-iit-soft-hand#20]
In [soft_hand_hw.cpp](https://github.com/CentroEPiaggio/pisa-iit-soft-hand/blob/master/soft_hand_ros_control/src/soft_hand_hw.cpp#L255-L256) the `joint_position_prev` update is incorrect: the `joint_position` has been converted to percent value in the previous iteration, thus it should not be divided by `17000` again.

    this->device_->joint_position_prev[j] = this->device_->joint_position[j]/17000;
    this->device_->joint_position[j] = inputs[0]/17000.0;

Fix:

    this->device_->joint_position_prev[j] = this->device_->joint_position[j];
    this->device_->joint_position[j] = inputs[0]/17000.0;

**Comment by hamalMarino** [comment]
You're right, if you can make a PR solving this I will merge it right away, thanks!
