### ISSUE TITLE
Which version Gazebo to use?

### ISSUE THREAD

**Issue by mjm522** [CentroEPiaggio/pisa-iit-soft-hand#22]
Hi,

I am currently running gazebo 2.2.3 with Ros Indigo.

I am getting following compile time error for the gazebo_ros_soft_hand_package. 

_hw_sim.cpp:739:27: error: ‘class gazebo::physics::Joint’ has no member named ‘SetPosition’
     sim_joints_mimic_[j]->SetPosition(0, joint_position_command_mimic_[j]);
and similar other errors.

With a quick google search, I understand this is a gazebo version problem. Could you please tell me which gazebo to use?

**Comment by hamalMarino** [comment]
Hi @mjm522 ,

This package has been tested since `gazebo4`, but I'd suggest getting the latest possible version you can use, as there have been lots of improvements on that side over time.
