### ISSUE TITLE
Manage internal hand collisions

### ISSUE THREAD

**Issue by hamalMarino** [CentroEPiaggio/pisa-iit-soft-hand#7]
As of now the hand has disabled selfCollision, which is necessary due to the structure with mimic joints (and fake links in between) which won't be neglected when considering collisions.
Nonetheless, far apart links should be colliding with the others in order to avoid useless compenetration.

This could probably be fixed with a (clever) update of the link geometries, but needs thorough thinking.
@arocchi @carlosjoserg

**Comment by hamalMarino** [comment]
This could be solved within Gazebo6, which has a new feature of [collide bitmask](http://gazebosim.org/tutorials?tut=collide_bitmask&cat=physics) implemented... @arocchi @carlosjoserg  would it be possible to go forward with Gazebo? Will we have too many compatibility issues?
This will need to be done soon enough anyway I guess...

**Comment by carlosjoserg** [comment]
Looks like a nice feature for what it is required. Pity it is not available as of Gazebo5, which is the official in Jade, and to where we should be migrating everything to soon as well. Mainly because we rely a lot in the gazebo_ros package and there are also nice features in ros control available only in Jade.

I suppose that if we migrate everything to Jade, the use of Gazebo6 will be smoother (hopefully) too.

Should we start a branch as `jade-migration`? (I'd prefer to keep a `master` branch with the current supporting system, and in that case we can simply tag the commit with `indigo-compatible` or something).

**Comment by arocchi** [comment]
@carlosjoserg, @hamalMarino I would like to stay in Indigo at least till the end of the current work we are doing, but I see the need for a migration plan. I would like to leave the details to you @carlosjoserg, and add a few practical points:
the feature Gazebo is exporting now is an interface to the underlying bitmasking which is done internally by ODE and the likes. What we could do is add some specific code in the `Load` method of `gazebo_ros_soft_hand_plugin` that does what Gazebo6 does also in previous Gazebo versions, directly in the plugin code. Again, it should not be difficult, and for sure it is trivial in ODE. By programming the feature in this way, SDF will be ready for Gazebo6 starting now, but we will have the same feature backported to the current setup.
This is related to #9, meaning that what we should do is provide an SDF of the hand (eventually, also precompiled) with the Gearbox and Surface elements inserted, by means of some script i guess..

What do you guys think?
I can start working on Gearboxes already tomorrow morning, maybe if we coordinate we could try this approach in parallel, so let's say I could give a stab at Gearboxes tomorrow morning and Wednesday morning we could coordinate to properly enable self-collisions.

PS: I suggest all the attemps we do with the modifications of the plugin are all logged, see the code in https://github.com/arocchi/pisa-iit-soft-hand/tree/original_plugin - This way we can compare the performances of the simulator. This will be valuable data later on. Better to have more than less ;)

**Comment by carlosjoserg** [comment]
The branch `cropped-collisions` contains one commit only that can be cherry-picked for testing with the collision geometries modified such that flexion joints do not touch.

**Comment by arocchi** [comment]
:+1:

**Comment by hamalMarino** [comment]
Had a look at them, @carlosjoserg , and they seem good geometries: I will test how it works as soon as we get #9

**Comment by hamalMarino** [comment]
Now they work decently both in Gazebo4 and Gazebo6 (the latter is solved in the right way, i.e. using collision bitmask), respectively in the branches `cropped-collisions` and `self-collisions-gazebo6`

@carlosjoserg @arocchi

**Comment by carlosjoserg** [comment]
:clap: :clap:  :clap:
